# Generated by Django 4.1.3 on 2022-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_file', models.FileField(upload_to='files/generic/')),
                ('file_to_compare', models.FileField(upload_to='files/file_to_compare/')),
            ],
        ),
    ]
