# Generated by Django 4.1.3 on 2022-11-11 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_compare', '0002_alter_compare_file_to_compare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctoPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_file', models.FileField(upload_to='files/doc_file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='UPLOAD WORD FILE : ')),
            ],
        ),
    ]
