# Generated by Django 4.1.3 on 2022-11-12 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_compare', '0003_doctopdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdftoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='files/pdf_file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='UPLOAD PDF FILE : ')),
            ],
        ),
    ]
